language: php
php:
#  - '5.3'
#  - '5.4'
#  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

sudo: false

install:
  - composer install --no-interaction

script:
# I don't trust preinstalled phpunit version, didn't executed tests for php7 at all
  - /bin/bash phpunit --stop-on-failure

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'